stages:

  training_model:
    cmd: python src/Project_1/pipeline/stage1_training_model.py
    deps:
      - src/Project_1/pipeline/stage1_training_model.py
      - configs/config.yaml
      - data
    params:
      - AUGMENTATION
      - IMAGE_SIZE
      - BATCH_SIZE
      - EPOCHS
      - N_CLASSES
      - N_SEGMENT
      - LEARNING_RATE
      - SEED
      - IN_CHANNELS
      - TASK_NUM
      - NUM_WORKERS
      - PATIENCE
      - MODEL_NAME
    outs:
      - artifacts/training/model.pth

  evaluation_model:
    cmd: python src/Project_1/pipeline/stage2_evaluation_model.py
    deps:
      - src/Project_1/pipeline/stage2_evaluation_model.py
      - configs/config.yaml
      - artifacts/training/model.pth
      - data
    params:
      - BATCH_SIZE
      - IMAGE_SIZE
      - NUM_WORKERS
      - SEED
      - N_CLASSES
      - N_SEGMENT
      - IN_CHANNELS
    metrics:
      - artifacts/evaluation_model/report.json